"""
Document question schemas – defines what the AI must ask per document type.
AI only collects these fields; legal text comes from templates.
"""

DOCUMENT_QUESTIONS = {
    "rental_agreement": [
        {"field": "owner_name",      "question": "What is the full name of the property owner (Landlord)?"},
        {"field": "owner_address",   "question": "What is the complete address of the owner?"},
        {"field": "tenant_name",     "question": "What is the full name of the tenant?"},
        {"field": "tenant_address",  "question": "What is the tenant's permanent address?"},
        {"field": "property_address","question": "What is the full address of the property being rented?"},
        {"field": "monthly_rent",    "question": "What is the monthly rent amount (in ₹)?"},
        {"field": "deposit_amount",  "question": "What is the security deposit amount (in ₹)?"},
        {"field": "duration_months", "question": "What is the duration of the agreement (in months)?"},
        {"field": "start_date",      "question": "What is the start date of the rental? (e.g. 01 June 2025)"},
        {"field": "notice_period",   "question": "What is the notice period required for vacating? (e.g. 1 month)"},
        {"field": "witness1_name",   "question": "What is the name of Witness 1?"},
        {"field": "witness2_name",   "question": "What is the name of Witness 2?"},
    ],
    "affidavit": [
        {"field": "deponent_name",    "question": "What is the full name of the person making the affidavit (Deponent)?"},
        {"field": "deponent_age",     "question": "What is the Deponent's age?"},
        {"field": "deponent_address", "question": "What is the Deponent's full address?"},
        {"field": "deponent_id",      "question": "What is the Deponent's Aadhaar/Voter ID number?"},
        {"field": "purpose",          "question": "What is the purpose of this affidavit? (briefly describe)"},
        {"field": "statement",        "question": "What is the main statement or declaration to be made in the affidavit?"},
        {"field": "place",            "question": "In which city/district is this affidavit being executed?"},
        {"field": "date",             "question": "What is the date of execution? (e.g. 17 May 2025)"},
        {"field": "witness1_name",    "question": "What is the name of Witness 1?"},
        {"field": "witness2_name",    "question": "What is the name of Witness 2?"},
    ],
    "power_of_attorney": [
        {"field": "principal_name",    "question": "What is the full name of the Principal (person granting power)?"},
        {"field": "principal_address", "question": "What is the Principal's full address?"},
        {"field": "principal_id",      "question": "What is the Principal's Aadhaar/ID number?"},
        {"field": "agent_name",        "question": "What is the full name of the Agent (person receiving power)?"},
        {"field": "agent_address",     "question": "What is the Agent's full address?"},
        {"field": "agent_id",          "question": "What is the Agent's Aadhaar/ID number?"},
        {"field": "powers_granted",    "question": "What specific powers are being granted? (e.g. sell property, manage bank account)"},
        {"field": "property_details",  "question": "Describe the property or assets involved (if any)."},
        {"field": "duration",          "question": "Is this a General POA (no expiry) or specify duration/expiry date."},
        {"field": "place",             "question": "In which city/district is this being executed?"},
        {"field": "date",              "question": "What is the execution date? (e.g. 17 May 2025)"},
        {"field": "witness1_name",     "question": "What is the name of Witness 1?"},
        {"field": "witness2_name",     "question": "What is the name of Witness 2?"},
    ],
    "sale_agreement": [
        {"field": "seller_name",       "question": "What is the full name of the Seller?"},
        {"field": "seller_address",    "question": "What is the Seller's full address?"},
        {"field": "buyer_name",        "question": "What is the full name of the Buyer?"},
        {"field": "buyer_address",     "question": "What is the Buyer's full address?"},
        {"field": "property_address",  "question": "What is the full address/description of the property being sold?"},
        {"field": "survey_no",         "question": "What is the Survey Number / Plot Number of the property?"},
        {"field": "sale_price",        "question": "What is the total agreed sale price (in ₹)?"},
        {"field": "advance_paid",      "question": "What is the advance/token amount already paid (in ₹)?"},
        {"field": "balance_due",       "question": "What is the balance amount due at registration?"},
        {"field": "completion_date",   "question": "By what date should the full payment and registration be completed?"},
        {"field": "witness1_name",     "question": "What is the name of Witness 1?"},
        {"field": "witness2_name",     "question": "What is the name of Witness 2?"},
    ],
    "loan_agreement": [
        {"field": "lender_name",       "question": "What is the full name of the Lender?"},
        {"field": "lender_address",    "question": "What is the Lender's full address?"},
        {"field": "borrower_name",     "question": "What is the full name of the Borrower?"},
        {"field": "borrower_address",  "question": "What is the Borrower's full address?"},
        {"field": "loan_amount",       "question": "What is the loan amount (in ₹)?"},
        {"field": "interest_rate",     "question": "What is the agreed interest rate? (e.g. 12% per annum or interest-free)"},
        {"field": "duration_months",   "question": "What is the loan duration (in months)?"},
        {"field": "repayment_schedule","question": "What is the repayment schedule? (e.g. monthly installments of ₹5000)"},
        {"field": "loan_purpose",      "question": "What is the purpose of this loan?"},
        {"field": "date",              "question": "What is the agreement date? (e.g. 17 May 2025)"},
        {"field": "witness1_name",     "question": "What is the name of Witness 1?"},
        {"field": "witness2_name",     "question": "What is the name of Witness 2?"},
    ],
}

DOCUMENT_LABELS = {
    "rental_agreement":  "Rental Agreement",
    "affidavit":         "Affidavit",
    "power_of_attorney": "Power of Attorney",
    "sale_agreement":    "Sale Agreement",
    "loan_agreement":    "Loan Agreement / Bond",
}
