"""PDF generation service using ReportLab."""

import os
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from config import settings
from templates.english_templates import TEMPLATE_MAP
from templates.malayalam_templates import TEMPLATE_MAP_ML, generic_ml
from services.document_schemas import DOCUMENT_LABELS

# Try to register a Unicode font for Malayalam (fallback to Helvetica)
MALAYALAM_FONT = "Helvetica"
try:
    # Try Noto Sans Malayalam if available on system
    font_paths = [
        "C:/Windows/Fonts/NotoSansMalayalam-Regular.ttf",
        "C:/Windows/Fonts/Arial Unicode MS.ttf",
    ]
    for fp in font_paths:
        if os.path.exists(fp):
            pdfmetrics.registerFont(TTFont("UniFont", fp))
            MALAYALAM_FONT = "UniFont"
            break
except Exception:
    pass


def _build_english_pdf(doc_type: str, form_data: dict, stamp_value: int, output_path: str):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    DARK_BLUE = colors.HexColor("#1a2a5e")
    GOLD = colors.HexColor("#c8a951")

    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=16, textColor=DARK_BLUE,
        spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "Sub", parent=styles["Normal"],
        fontSize=10, textColor=GOLD,
        spaceAfter=4, alignment=TA_CENTER,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, leading=16,
        spaceAfter=6, fontName="Helvetica",
    )
    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=9, textColor=colors.grey, fontName="Helvetica-Bold",
    )

    doc_label = DOCUMENT_LABELS.get(doc_type, doc_type.replace("_", " ").title())
    template_fn = TEMPLATE_MAP.get(doc_type)
    if not template_fn:
        text = "Document template not found."
    else:
        text = template_fn(form_data, stamp_value)

    story = []

    # Header
    story.append(Paragraph("LEGAL SEVA KERALA", title_style))
    story.append(Paragraph("AI-Powered Legal Document Services", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=DARK_BLUE, spaceAfter=12))

    story.append(Paragraph(doc_label.upper(), title_style))
    story.append(Paragraph(f"Stamp Paper Value: ₹{stamp_value}", subtitle_style))
    story.append(Spacer(1, 12))

    # Document body – split on newlines
    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
        else:
            story.append(Paragraph(stripped, body_style))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Paragraph("Generated by LegalSeva Kerala | This is a draft document for review purposes.", label_style))

    doc.build(story)


def _build_malayalam_pdf(doc_type: str, form_data: dict, stamp_value: int, output_path: str):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    DARK_BLUE = colors.HexColor("#1a2a5e")
    GOLD = colors.HexColor("#c8a951")
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleML", fontName=MALAYALAM_FONT, fontSize=15,
        textColor=DARK_BLUE, alignment=TA_CENTER, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyML", fontName=MALAYALAM_FONT, fontSize=10,
        leading=18, spaceAfter=4,
    )
    label_style = ParagraphStyle(
        "LabelML", fontName=MALAYALAM_FONT, fontSize=8,
        textColor=colors.grey,
    )

    doc_label = DOCUMENT_LABELS.get(doc_type, doc_type)
    template_fn = TEMPLATE_MAP_ML.get(doc_type)
    if template_fn:
        text = template_fn(form_data, stamp_value)
    else:
        text = generic_ml(doc_label, form_data, stamp_value)

    story = []
    story.append(Paragraph("ലീഗൽ സേവ കേരള", title_style))
    story.append(Paragraph("AI നിയമ രേഖ സേവനങ്ങൾ", title_style))
    story.append(HRFlowable(width="100%", thickness=2, color=DARK_BLUE, spaceAfter=12))
    story.append(Spacer(1, 8))

    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 5))
        else:
            try:
                story.append(Paragraph(stripped, body_style))
            except Exception:
                story.append(Paragraph(stripped.encode("ascii", "replace").decode(), body_style))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Paragraph("LegalSeva Kerala | ഡ്രാഫ്റ്റ് രേഖ", label_style))

    doc.build(story)


def generate_pdfs(doc_id: str, doc_type: str, form_data: dict, stamp_value: int) -> dict:
    """Generate both English and Malayalam PDFs. Returns paths."""
    pdf_dir = Path(settings.PDF_DIR)
    pdf_dir.mkdir(exist_ok=True)

    en_path = str(pdf_dir / f"{doc_id}_en.pdf")
    ml_path = str(pdf_dir / f"{doc_id}_ml.pdf")

    _build_english_pdf(doc_type, form_data, stamp_value, en_path)
    _build_malayalam_pdf(doc_type, form_data, stamp_value, ml_path)

    return {"en": en_path, "ml": ml_path}
